Fix CPUID availability test for x86_64.
Before you got following gcc/clang error in x86_64:

    cputest.c: Assembler messages:
    cputest.c:38: Error: suffix or operands invalid for `pop'
    cputest.c:41: Error: suffix or operands invalid for `push'
    cputest.c:44: Error: suffix or operands invalid for `pop'

"=a" (int32_t) ties %N to 32-bit register, thus eax is obligatorily used
also in 64-bit code. Maybe it's debatable behaviour, but let's leave it.
So what's the problem with pop/push, is popl/pushl eax incorrect in x64?
Exactly! Doubts? See: http://www.x86-64.org/documentation/assembly.html.

There is no need to use preprocessor and clutter this simple code.
Introducing dummy long variable in "a" guarantees that %N will be tied
with with register of processor's word size, i.e. rax in x64. Cost of
this simplification is compiler spitting useless xor eax,eax in front of
the asm block (at least in gcc 4.4), but it's really negligible.

In the end we get same asm block output in x86 and x86_64: (xor)

    (31 c0) 9c 58 89 c1 35 00 00 20 00 50 9d 9c 58

Signed-off-by: Przemyslaw Pawelczyk <przemoc@gmail.com>